fullname = "John Doe"

[defaults]
path = "."
git = true
docker = false
entry = "main"
gitignore = true
license = "MIT"
github = false
public = false

[python]
version = "3.13"
pm = "uv"
linter = "black"
pytest = false
git = false

[js]
version = "24"
pm = "pnpm"

[java]
version = "21"
build = "gradle"

[c]
standard = "c23"
compiler = "gcc"
build = "cmake"

[cpp]
standard = "c++23"
compiler = "g++"
build = "cmake"

[rust]
toolchain = "stable"

[go]
version = "1.25"

[swift]
version = "6"

[csharp]
version = "12"